;;; ent-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ent.el

(autoload 'ent-run "ent" "\
Main entry point for ent.
You could specify the TASKNAME.

(fn &optional TASKNAME)" t)
(autoload 'ent-visit-build-file "ent" "\
Visit the ent project file." t)
(autoload 'ent-visit-config-file "ent" "\
Visit the project specific config file, ent-project-config-filename." t)
(autoload 'ent-find-file "ent" "\
Find a file from the project." t)
(defvar ent-prefix-map (let ((map (make-sparse-keymap))) (define-key map "x" 'ent-run) (define-key map "c" 'ent-visit-config-file) (define-key map "b" 'ent-visit-build-file) (define-key map "f" 'ent-find-file) map))
(fset 'ent-prefix-map ent-prefix-map)
(register-definition-prefixes "ent" '("ent-" "task"))


;;; Generated autoloads from ent-elisp-tasks.el

(register-definition-prefixes "ent-elisp-tasks" '("ent-"))

;;; End of scraped data

(provide 'ent-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ent-autoloads.el ends here
