;;; lisp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ent.el

(autoload 'ent-run "ent" "\
Main command, run the selected task and all of its dependencies recursively.

When invoked interactively, `ent-run` first loads the project‑specific
config file (`ent-project-config-filename').  It then asks the user to pick
a task from the list of registered tasks, resolves that task’s
`:deps` field recursively, and finally executes the task itself." t)
(register-definition-prefixes "ent" '("ent-"))


;;; Generated autoloads from ent-default-tasks.el

(register-definition-prefixes "ent-default-tasks" '("ent-"))


;;; End of scraped data

(provide 'lisp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; lisp-autoloads.el ends here
